### ISSUE TITLE
Replace the term Vaadin Connect with Vaadin

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow-and-components-documentation#1001]
Replace the term Vaadin Connect with Vaadin in the docs, as there is only one product Vaadin.

DoD:
No Vaadin Connect in the docs.

**Comment by vlukashov** [comment]
![image.png](https://images.zenhubusercontent.com/5a572ab64b5806bc2bc2536e/1d2bb4ac-413d-42ea-a2d5-370c541b257f)
