### ISSUE TITLE
Avoid extending UI

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow-and-components-documentation#101]
There are some examples that are showing code that extend `UI`. These are no longer appropriate with the "new" router, and should thus be updated to show how things are done without a custom `UI` subclass. The cases are listed in [this search listing](https://github.com/vaadin/flow-and-components-documentation/search?utf8=%E2%9C%93&q=%22extends+UI%22&type=).

**Comment by denis-anisimov** [comment]
`3-general-differences.asciidoc`  is not changed since it is exactly how to use `UI`  if you really really want to do it in the old fashioned way.
