### ISSUE TITLE
v15 accessing backend documentation should mention @AnonymousAllowed

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow-and-components-documentation#1076]
The start.vaadin.com -generated Endpoints have the `@AnonymousAllowed` annotation in them. The documentation at 
https://vaadin.com/docs/v15/flow/typescript/accessing-backend.html doesn't mention this annotation at all, it should probably be mentioned there.

**Comment by haijian-vaadin** [comment]
DoD:
Add `@AnonymousAllowed` in the code example, explain briefly why it's needed.
