### ISSUE TITLE
Document styling Grid with Grid.setClassNameGenerator

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow-and-components-documentation#1098]
There's no mention of styling a V10+ Grid rows or cells with Grid.setClassNameGenerator or Grid.Column.setClassNameGenerator in vaadin.com/docs or vaadin.com/components/vaadin-grid

**Comment by web-padawan** [comment]
Should be fixed here: https://github.com/vaadin/vaadin-grid-flow/issues/878

**Comment by web-padawan** [comment]
Closing this one as a duplicate.
