### ISSUE TITLE
Document the need to import components when using them with a template renderer.

### ISSUE THREAD

**Issue by web-padawan** [vaadin/flow-and-components-documentation#1106]
Originally submitted as https://github.com/vaadin/vaadin-grid-flow/issues/489

The following quote contains a user feedback from https://github.com/vaadin/vaadin-grid-flow/issues/489#issuecomment-457252466

> That being said, I'm sure others will run into the same issue. I don't recall having seen any notes about having to manually import vaadin-* components when using them with a template renderer.

> It would be good to have a note in the Flow documentation

We should make it clear that components have to be imported in this case.

**Comment by Legioth** [comment]
Please note that the documentation should use `@Uses` rather than duplicating `@JsModule` or `@HtmlImport` annotations from the desired component.
