### ISSUE TITLE
Create V16 branch

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/flow-and-components-documentation#1198]
- Make sure that pnpm is the default front-end build tool in master before creating V16 branch out of master.
- It should not include documents related to features that are not going to be in V16 like live reload and URL parameters.

**Comment by denis-anisimov** [comment]
>Make sure that pnpm is the default front-end build tool in master before creating V16 branch out of master.

It's not the default.
And I don't understand what should I do with this : fix `master` branch or make it default in `V16`  ?
Does `master` target `3.0`  Flow ?

**Comment by mehdi-vaadin** [comment]
`master` targets Vaadin 16 at the moment. After `V16` branch is created, `master` should target Vaadin 17 and Flow 3.2.

**Comment by denis-anisimov** [comment]
OK.
And........ ?
Does it mean that I should fix `master` to make `pnpm` default as well ?

**Comment by mehdi-vaadin** [comment]
>Does it mean that I should fix master to make pnpm default as well ?

Yes, you should do it before creating V16 branch.

**Comment by denis-anisimov** [comment]
OK, thanks. But I think I will do it in `V16`  and use it to make a PR for the `master`: it still requires a PR so why not use `V16` for this ?

**Comment by mehdi-vaadin** [comment]
Yes, good idea :)

**Comment by mehdi-vaadin** [comment]
This is a recent commit that includes changes related to `npm` being the default in Vaadin `14.2`: https://github.com/vaadin/flow-and-components-documentation/commit/50a2611cd86b2f587501cedce1ea04a11865d06b. It may give you ideas about where you need to change.

**Comment by denis-anisimov** [comment]
Aright, thanks !
