### ISSUE TITLE
Update Lumo docs links to 1.0 final

### ISSUE THREAD

**Issue by jouni** [vaadin/flow-and-components-documentation#121]
Some of the links point to 1.0 alpha3.

**Comment by jouni** [comment]
Some of the links are in Bakery App Starter docs.

**Comment by denis-anisimov** [comment]
Could you please give me an example ?
I cannot find any references to Lumo 1.0 alpha3.
Do we have any versions mentioned in docs at all? I thought it's just a `Lumo.class` reference and that's it.

**Comment by jouni** [comment]
Sorry, it might be that all the links, which I saw, were actually in the Bakery documentation.

I didn’t spot any old links at the moment. But kudos on already updating the Material theme link to 0.4.0 version 👏 

I’ll close this as invalid/fixed.
