### ISSUE TITLE
Cumbersome list and sentence structure

### ISSUE THREAD

**Issue by jouni** [vaadin/flow-and-components-documentation#124]
On https://vaadin.com/docs/v10/flow/theme/using-component-themes.html

The first list contains rules how a theme is selected. The last point is just a conclusion of the above, so it should not be contained in the list, but just a regular paragraph after the list (which is actually already there after the list).

Also, the sentence structure is cumbersome as an “if all are not”. Would probably be easier to understand as an “if none are” (since the “not“ is very disconnected from “all”).

> If all the previous conditions are not met, no theme is used.
vs.
> If none the previous conditions are met, no theme is used.

**Comment by DiegoSanzVi** [comment]
This PR fixed the issue:  https://github.com/vaadin/flow-and-components-documentation/pull/361.
