### ISSUE TITLE
Missing word on Book of Vaadin 14

### ISSUE THREAD

**Issue by pigbar** [vaadin/flow-and-components-documentation#1242]
At page 139 of Book of Vaadin, there is a missing "use" word.
It is:
Flexible Filtering Using a Predicate Parameter
You **can a predicate** parameter in your service methods to
implement flexible filtering.

It should be:
Flexible Filtering Using a Predicate Parameter
You **can use a predicate** parameter in your service methods to
implement flexible filtering.

**Comment by anasmi** [comment]
Closing the issue as pr was merged. Thank you for reporting! :)
