### ISSUE TITLE
App created in flow tutorial does not have a good filter text field

### ISSUE THREAD

**Issue by johannesh2** [vaadin/flow-and-components-documentation#17]
Flow tutorial mentions 

> As its name implies, the value change listener allows you to react to changes in the value contained in the text field. It is configured so that the event is fired lazily while the user is typing, when there is a small pause in the typing. This makes it perfect for this kind of automatic filtering.

If I'm not mistaken the tutorial creates a text field that applies value change in blur, which is not optimal for search field and not as advertised in tutorial.

**Comment by pleku** [comment]
This is for the getting started tutorial.
