### ISSUE TITLE
Identifications - Create V10 docs PDF

### ISSUE THREAD

**Issue by mikkoi-vaadin** [vaadin/flow-and-components-documentation#180]
Marketing is kicking off a project to [increase website identifications](https://docs.google.com/document/d/1hXhV0ac5O992ppYD4EBt5AyKnc4A096yF_dd1wz2064/edit?ts=5b047485#). 

V8 book PDF has performed very well. We should offer similar PDF for V10 (though it is not a book but docs collection).  

Please create V10 documentation PDF.

**Comment by mikkoi-vaadin** [comment]
This should be autogenerated and updated on every docs update

**Comment by pleku** [comment]
Handled by BoV project and will be available in the upcoming months. Since nobody will update this issue anyway, I'll just close it now.
