### ISSUE TITLE
Missing Docs on how to support Internet Explorer 11

### ISSUE THREAD

**Issue by appreciated** [vaadin/flow-and-components-documentation#201]
When building an addon using `PolymerTemplate` (or maybe even generally), by default the addon won't be able to run under IE 11. 

- This fact is I believe not mentioned in the documentation.
- There is no documentation how to support IE 11.

**Comment by Legioth** [comment]
This is indirectly covered through the production mode documentation: https://github.com/vaadin/flow-and-components-documentation/tree/master/documentation/production

There are, however, two issues
* Seems like that those documents are for some reason missing from vaadin.com/docs (or then I just look in the wrong place)
* It could also be good to have some references to this information in the documentation about `PolymerTemplate`.
