### ISSUE TITLE
Tutorial broken links 

### ISSUE THREAD

**Issue by mikkoi-vaadin** [vaadin/flow-and-components-documentation#294]
All the three links in this second part of the tutorial lead to 404 

https://vaadin.com/docs/v10/flow/introduction/tutorial-get-started-second-part.html

![image](https://user-images.githubusercontent.com/26737661/46145195-1173f700-c268-11e8-9400-0b5c9c28d567.png)

**Comment by tmattsso** [comment]
fixed

**Comment by tmattsso** [comment]
@pleku how should this be handled, PR #290 fixed it.

**Comment by gilberto-torrezan** [comment]
If it's fixed, it's fixed. Closing it now.
