### ISSUE TITLE
remove the word 'vaadin' from all top-level documentation menu items

### ISSUE THREAD

**Issue by tmattsso** [vaadin/flow-and-components-documentation#331]
the menu on this page (https://vaadin.com/docs ) has a lot of redundant 'vaadin' prefixes; they should be removed.

**Comment by pleku** [comment]
@tmattsso those are not declared in the flow documentation, but in https://github.com/vaadin/vaadin-docs/

**Comment by pleku** [comment]
Issue moved to [vaadin/vaadin-docs #139](https://github.com/vaadin/vaadin-docs/issues/139) via [**ZenHub**](https://www.zenhub.com/)
