### ISSUE TITLE
Spring tutorial for V11 has a bug

### ISSUE THREAD

**Issue by tmattsso** [vaadin/flow-and-components-documentation#340]
this forum thread summarizes it:

https://vaadin.com/forum/thread/17374548/change-url-mapping-for-vaadin-flow-and-spring

"Changing the url as described on https://vaadin.com/docs/v11/flow/spring/tutorial-spring-configuration.html does not work on the https://vaadin.com/start/latest/project-base-spring. I have downloaded the starter app and only added "vaadin.urlMapping=/my_mapping/" to the application.properties file. To access the page I need to use this extra mapping now but the page is not rendered correctly and clicking on the "Click me" gives "Server connection lost"."

**Comment by DiegoSanzVi** [comment]
The reason why It does not work is that at the moment an additional servlet is required to handle webjars for non-root context. If a servlet is registered, it works.

**Comment by tmattsso** [comment]
fixed by https://github.com/vaadin/flow-and-components-documentation/pull/341
