### ISSUE TITLE
Document how to deploy a Flow app to Jetty

### ISSUE THREAD

**Issue by tmattsso** [vaadin/flow-and-components-documentation#352]
Should include how to configure Jetty for development mode, production mode (if it differs), and Spring.

**Comment by Legioth** [comment]
Why specifically for Jetty? What about all the other, more commonly used servlet containers out there?

**Comment by tmattsso** [comment]
Because we get a lot of questions about Jetty since it isn't straightforward. But sure, other containers should be added at some point as well.

**Comment by Legioth** [comment]
Using the Maven plugin, a standalone Jetty installation, or manually embedding?
