### ISSUE TITLE
Draft tutorials for keyboard shortcuts

### ISSUE THREAD

**Issue by pleku** [vaadin/flow-and-components-documentation#366]
Based on vaadin/flow#4870, draft tutorials for the use cases there on _how to add a focus shortcut_, how to add a click shortcut_ and _how to add a global shortcut_.

The tutorial should probably go into https://github.com/vaadin/flow-and-components-documentation/tree/master/documentation/components.

**Comment by bogdanudrescu** [comment]
This is the initial tutorial draft:

https://github.com/vaadin/flow-and-components-documentation/compare/bogdan-shortcut-tutorial
