### ISSUE TITLE
Use addThemeVariants in documentation

### ISSUE THREAD

**Issue by Peppe** [vaadin/flow-and-components-documentation#367]
Vaadin 12 brought us the handy `componentaddThemeVariants(String)` method for components. However in the documentation there is still usage of `button.getElement().setAttribute("theme", "contrast primary");
` at least in https://vaadin.com/docs/v12/flow/theme/using-component-themes.html. Update examples across the board to use the new API .

**Comment by DiegoSanzVi** [comment]
There was already a commit about it:  "Add theme variants documentation (#216)"

In the documentation, he mentioned the old way as an alternative,

"If you want more flexibility (which may come in handy when adding non-standard theme variants to the component), you can manipulate the value of the theme attribute directly:"

https://github.com/vaadin/flow-and-components-documentation/commit/b214e4105dcfe5f5637481e18d3cad3e5f347814#diff-268e59436474fb538c76d41f7c8715f8

Should this issue be closed?

**Comment by ZheSun88** [comment]
As Diego said, This ticket has been completed. closed.
