### ISSUE TITLE
Missing spring boot version

### ISSUE THREAD

**Issue by pierlon** [vaadin/flow-and-components-documentation#465]
In the [Use Flow with Spring](https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/spring/tutorial-spring-basic.asciidoc) tutorial, it's referring to a Spring Boot version property which has not yet been defined.

**Comment by anasmi** [comment]
Hi,

and thank you for submitting an issue! The dependency of spring was removed from the example with this pull request :https://github.com/vaadin/flow-and-components-documentation/commit/a81524c713b6010267fbaa5f386535896fb615c3#diff-de39fcebaf8d8dc3b7f61348bcb38da1 , therefore, I will close the issue. Please, let us know, if you would like it to be re-open for some reason. Thanks again :)
