### ISSUE TITLE
Restructure and improve embedding documentation based on DX

### ISSUE THREAD

**Issue by pleku** [vaadin/flow-and-components-documentation#586]
Based on DX testing
1) Move the tutorial to be the last page for embedding Flow
2) Add a new first page which:
- describes on high level why Flow applications sometimes need to be embedded
- describes on high level how it is achieved by embedding it as a web component
- describes on high level how it works technically - you have a component and you need to export it, configure properties and then configure an instance.
- lists all the following documentation topics which go through the features and also highlight the step-by-step tutorial in as the last thing

**Comment by ujoni** [comment]
> "you can embed Flow to into a non-Vaadin Application."

1) Is it so that it wouldn't work in a V8- app? If so, why?
2) When should we expect to have Flow-into-Flow support? Asking for a friend

DO:
Both 1 and 2 are doable. Should be clarified. Should an example be provided?

**Comment by pleku** [comment]
> Should an example be provided?

I don't think we need this at the moment

**Comment by ujoni** [comment]
### Acceptance criteria:
1) The long example is moved as the last item in the embedding tutorial
2) A new introduction page is introduced providing the following information:
    - describes on high level why Flow applications sometimes need to be embedded
    - describes on high level how it is achieved by embedding it as a web component
    - describes on high level how it works technically - you have a component and you need to export it, configure properties and then configure an instance.
    - lists all the following documentation topics which go through the features and also highlight the step-by-step tutorial in as the last thing

**Comment by ZheSun88** [comment]
and remember to check https://github.com/vaadin/flow-and-components-documentation/issues/636

**Comment by ujoni** [comment]
Oh, I wasn't even aware that is a thing. How official are we about that? Is `application - navigation = component`?  Or just a small application?

**Comment by Legioth** [comment]
Yes, it's the lack of navigation and other related stuff that is relevant there.
