### ISSUE TITLE
Fix documentation about integrating a web component

### ISSUE THREAD

**Issue by pleku** [vaadin/flow-and-components-documentation#590]
The documentation for integrating a web component is not up to date https://github.com/vaadin/flow-and-components-documentation/tree/2.0/documentation/web-components

It is e.g. using the `NpmPackage` annotation without `version` property.
Also e.g. the code about adding a click listener isn't using the proper generics it should, it should be like:
```
    public Registration addClickListener(ComponentEventListener<ClickEvent<PaperSlider>> listener) {
        return addListener(ClickEvent.class, (ComponentEventListener) listener);
    }
```
After the component starter that should be the base of the tutorials has been fixed to work on Flow 2.0,
go through the integrating a web component documentation and make sure that it is too up to date with the latest Flow 2.0.

**Comment by bogdanudrescu** [comment]
@pleku `ClickEvent` is already defined as `ClickEvent extends ComponentEvent<PaperSlider>`
