### ISSUE TITLE
Include P3 related theming / styling instructions

### ISSUE THREAD

**Issue by pleku** [vaadin/flow-and-components-documentation#602]
Add a new documentation page with topic like "Changes in theming for Polymer 3 (npm)" to https://github.com/vaadin/flow-and-components-documentation/tree/master/documentation/theme.

It should describe all the things required to be able to theme P3 based web components and templates in Vaadin 14 and how it differs from https://github.com/vaadin/beverage-starter-flow/blob/master/frontend/styles/shared-styles.js and https://github.com/vaadin/beverage-starter-flow/blob/master/src/main/java/com/vaadin/starter/beveragebuddy/ui/MainLayout.java#L38.

This documentation should answer the users question: what do I need to do differently compared to V10-13 (P2).

Other theming documentation files should be preferably updated to use the new P3 syntax.

**Comment by pleku** [comment]
There is some work already done here https://github.com/vaadin/flow-and-components-documentation/pull/577 but it contains some additional things that are not implemented yet (the new theming features for Flow)

**Comment by ujoni** [comment]
### DRAFT Acceptance criteria:
- Users are able to understand what actions they'll need to take for their P2 themes to become P3 themes using the "Changes in theming for Polymer 3 (npm)" tutorial 
  - Answers the question "what do I need to do differently compared to V10-13 (P2)?"
- Migration tutorial should link to the new tutorial page

**Comment by Haprog** [comment]
The migration page here https://github.com/vaadin/flow-and-components-documentation/blob/38b973cc044c224f11237decb9b7f3be16e99a90/documentation/v14-migration/v14-migration-guide.asciidoc#styles

now mentions migrating `custom-style` but it should probably also mention that the same approach works for `dom-module` (e.g. `theme-for`) as well (preferably with an example).
