### ISSUE TITLE
Rename the topic name to `Embedding flow Component`

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/flow-and-components-documentation#636]
Rename the topic `Embedding flow Applications` to `Embedding flow Components`, as you cannot embed a full app. 

Remember to change the line in https://github.com/vaadin/vaadin-docs/blob/vaadin14/website/_data/docs.yml#L35

**Comment by pleku** [comment]
We are not renaming the topic, as regardless of technicalities, you are still embedding a Vaadin app. It just won't have navigation. We'll make that more clear in the documentation, but in marketing terms, we will still talk about embedding Vaadin applications.
