### ISSUE TITLE
Polymer 2 to 3 migration guide

### ISSUE THREAD

**Issue by bsutton** [vaadin/flow-and-components-documentation#645]
With vaadin 14 out and an early version of the migration guide out it would be really nice to see:

Additional details on migrating polymer 2 to polymer 3.

The guide shouldn't assume that the user understands:
Npm
Bower
Webjars
Webpack

The guide should assume that the user has:
a basic understanding of polymer 2
A basic understanding of JavaScript

**Comment by pleku** [comment]
Hi Brian. We are going to make a migration tool that helps converting P2 templates into P3, but I think we've forgot to mention it in the document. Also probably we should highlight the compatibility mode and the fact that migration is not mandatory right in the beginning.

For npm, bower, webjars and webpack, I think there are reasonably good explanations about what they are about, and users are free to google those for discovering more. Mayhaps we could provide some links and reword the beginning of the document a bit on these too, but it does already say
>Do not be alarmed if you are not familiar with these files or the npm way of doing things. The invocation of npm is fully automated by vaadin-maven-plugin; the only thing you need to make sure is that Node.js (version 10 or later) and npm (version 5.6 or later) are installed. If they are not installed, vaadin-maven-plugin will halt and present you with the possible installation alternatives.

so I'm not entirely sure how we are assuming that the user understands these already.

**Comment by pleku** [comment]
I've tried to elaborate the concepts more and also added some more general details for existing users about the new toolset in 14 and migration with PR #650. Hopefully it helps.

**Comment by bsutton** [comment]
You have to remember that your client base are java developers that are
working in an eco system that has almost completely isolated them from the
JavaScript world and you are throwing them in the deep end.

After six months of working with flow I have a vague understanding of how
webjars work and no real understanding of webpack.

The feeling I'm left with from the vaadin documentation is that there are
two separate teams. One building flow and one building components and they
document their parts separately but there is little documentation on
combining the two. It is this area that is causing us the greatest trouble.

Here are some of the issues:
I tried to use polymer moduliser to upgrade my P2 components to p3 and was
prompted to create a Bower project.

Not to hard to work out but bower wanted an entry point, I had no idea what
to provide in the context of vaadin app, so I just made something up. We
need some guidance on this.

For some reason the moduliser converted some files  to .js but left some
has .html even though it made changes to them. No idea why.

The attempt to migrate to P3  opened up a whole slew of new questions.

The issues is how do you develop components with npm and vaadin.
Are we meant to create a npm project, do we need to have a local nmp
repository (is their such a thing?).

How does npm work with flow?
Is there any interaction at run time?
When you move to production what actions need to be taken?
How do javascript import/module statements work in production?
I've seen in the polymer 3 world that you can use @polymer for includes and
related statements that suggest that your web server needs to resolve these?
If I'm creating a polymer template can I use @polymer includes? How does
vaadin resolve these? When does it resolve these?
When I move to production mode my (vague) understanding is that often you
want to package javascript/templates/css into a single file (or a least
clusters) to improve startup time. Is this something vaadin supports, if so
how does it work. If not what are the recommended methods for optimising
flow for production.
How does http 2.0 affect this (I've seen that vaadin have made some
inconclusive experiments in this area).
When I start my flow application I see about 1.4MB of files downloaded, how
do I optimise these, it appears to download files that I don't think I'm
using.

It appears that If I want a vaadin polymer component added I need a jar for
the java and a jar for the javascript. The version no.s don't seem to match
and the documentation is scattered.

Sorry this has turned into a bit of a rant :)

Essentially there is much more than the simple mechanics of what needs to
be done to convert the project and the templates.

With 14 out I would expect to see a larger migration of vaadin developers
and right now their are some serious issues with the documentation that is
making any migration extremely difficult..

FWIW we have been developing with vaadin for about 7 years and have project
using 7,8 and flow.
The flow project started soon after 10 came out and we have been upgrading
as release have arrived.

Moving from 7/8 to flow has been a massive learning curve and the lack of
documentation a real impediment.

Brett
(but I still love vaadin ;).
