### ISSUE TITLE
Vaadin 13-14 upgrade instructions should be clearer

### ISSUE THREAD

**Issue by mstahv** [vaadin/flow-and-components-documentation#668]
Especially for Spring Boot users it appears to be hard to set the property. Instructions should explicitly say which line to add to their application.properties file.

Also, the instructions link to a separate page that lists all configuration properties, but it doesn't list the compatibilityMode

**Comment by pleku** [comment]
Fixed for both documentation pages https://vaadin.com/docs/v14/flow/v14-migration/v14-migration-guide.html#compatibility-mode
