### ISSUE TITLE
Document load order of @JsModule, @CssImport, @StyleSheet, @JavaScript resources

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow-and-components-documentation#706]
Update and describe clearly what is guaranteed regarding loading order both within  same annotations and different annotations:  
https://vaadin.com/docs/v14/flow/importing-dependencies/tutorial-ways-of-importing.html

Depends on:
https://github.com/vaadin/flow/issues/6198

May also want to mention that imports from `@Theme` come before all other imports. See:
https://github.com/vaadin/flow/issues/5729

**Comment by pleku** [comment]
This same documentation should explain how `@JavaScript` works too, related to https://github.com/vaadin/flow/issues/5945
