### ISSUE TITLE
integrating-a-web-component - source code not monitored

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/flow-and-components-documentation#713]
On this page: https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/web-components/integrating-a-web-component.asciidoc

> The vaadin-maven-plugin will automatically install the npm package in node_modules and import the JS module file into the document provided to the browser when running mvn clean install. Moreover, if the Jetty webserver is run from Maven (using mvn jetty:run), your project’s source code is monitored for changes to these types of annotations. So any change to @NpmPackage or @JsModule annotations will trigger installation of the referenced packages and hot deployment of your app including the new JS module imports.

It does not work with the add-on project. (with IntelliJ or in command line "mvn jetty:run").
Perhaps I need to configure something or is it because of the structure of the add-on (run the demo in the test package) ?

**Comment by caalador** [comment]
The sources should update on runtime as long as the project is not a multi-module and the Jetty plugin has the scanInterval > 0

**Acceptance Criteria:**
- [ ] Starter scanInterval should be set to 3s
- [ ] Documentation note about multimodule should explain that code changes will then not be considered.
