### ISSUE TITLE
Migrating WebJars to NPM not found in the documentation

### ISSUE THREAD

**Issue by paulroemer** [vaadin/flow-and-components-documentation#715]
I wasn't able to find any hint on how to migrate 3rd party WebJars to NPM. I also have the feeling that the migration tools is not prepared for it.

Steps:
- remove WebJars from POM
- add `@NpmPackage(value = "@polymer/iron-form", version = "3.0.1")` or
- update package.json (I guess)

**Comment by mehdi-vaadin** [comment]
### Acceptance criteria
The v14 migration guide should include instructions on how to migrate WebJar dependencies to npm packages. It should mention the following.
- [ ] Removing WebJar dependency from pom.xml
- [ ] How to find the equivalent npm package
- [ ] Adding `NpmPackage` annotation to the class where it's used
