### ISSUE TITLE
Theme preset snippet doesn't work

### ISSUE THREAD

**Issue by qtdzz** [vaadin/flow-and-components-documentation#721]
In theming documentation for v14, the following snippet is provided to use the compact preset which is apparently incorrect by default (npm mode):
```
@JsModule("frontend://bower_components/vaadin-lumo-styles/presets/compact.js")
@Theme(Lumo.class)
public class CompactMainLayout extends Div
        implements RouterLayout {
}
```
https://vaadin.com/docs/v14/flow/theme/using-component-themes.html#using-vaadin-theme-presets

**Comment by anasmi** [comment]
Hi,

thank you for reporting the issue! I have take a look and documentation has been fixed and includes now the correct annotation
`@JsModule("@vaadin/vaadin-lumo-styles/presets/compact.js")`

I will close this ticket due to that, but ,please, let us know if I have missed anything!
