### ISSUE TITLE
V8 to V14 migration docs need to be updated

### ISSUE THREAD

**Issue by vesanieminen** [vaadin/flow-and-components-documentation#724]
Some documentation fixes need to be done under https://vaadin.com/docs/v14/flow/migration/1-migrating-v8-v10.html

1. https://vaadin.com/docs/v14/flow/migration/2-migration-strategies.html <- this should be rewritten to change V10 -> V10+ / V14 and change the mention to MPR being in development to being available
2. https://vaadin.com/docs/v14/flow/migration/5-components.html <- this should be updated to reflect what has been released instead of mention what is planned
3. https://vaadin.com/docs/v14/flow/migration/8-migration-example.html <- Step 6 - Production Mode sounds like a Bower construct so likely that should be removed?
4. The heading should be changed from V10 to V14?
![Screen Shot 2019-08-12 at 10 41 37](https://user-images.githubusercontent.com/108755/62851140-db0f6100-bced-11e9-9f4a-21f7ebcc494d.png)

**Comment by Ansku** [comment]
I kind of feel like we should have a different set of docs for V10 and V14, even if they are mostly identical.
