### ISSUE TITLE
Theme documentation for Vaadin 14

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin/flow-and-components-documentation#730]
In this page https://vaadin.com/docs/v14/flow/theme/using-component-themes.html ,these 3 links are not up-to-date (references to bower) in the quoted paragraph.

> Both themes provide some customization points for the components, that allow you to fine tune the look and provide a better UX. It can be customized by using CSS custom properties, see the Lumo documentation and the Material documentation for more information. The theming for the Vaadin components is built using Vaadin.ThemableMixin. See vaadin-themable-mixin wiki to learn how theming of Vaadin components is done.

* https://vaadin.com/themes/material 
* https://cdn.vaadin.com/vaadin-lumo-styles/1.5.0/demo/
* https://github.com/vaadin/vaadin-themable-mixin/wiki

This paragraph:
> For looking up all available component variants, see the component HTML examples and look under the Lumo Theme tab for examples of the variants.

I didn’t find the available component variants in this link. Few variants for the grid, button and not under “Lumo Theme Tab”.

If I just follow the documentation https://vaadin.com/docs/v14/flow/theme/using-component-themes.html , MyTheme is empty and I cannot test variant. 

In this page: https://vaadin.com/docs/v14/flow/theme/theming-crash-course.html

There is no Java class to test my-view.js so to try this I have to find how to include a  polymerTemplate in Java and create the right Java class.

My-view.css is not used (where should I import this file? It's not explained in the doc).

At the end of the documentation, I don't have MyView with the "right" color (brown).

**Comment by jouni** [comment]
Improvements to themes and styling documentation are coming in #1027
