### ISSUE TITLE
Importing HTML and JavaScript chapter seems to be outdated

### ISSUE THREAD

**Issue by johannesh2** [vaadin/flow-and-components-documentation#778]
The documentation in [/v14/flow/importing-dependencies/tutorial-importing.html](https://vaadin.com/docs/v14/flow/importing-dependencies/tutorial-importing.html)
Mentions HtmlImport and does not mention JsModule. There should be explained where the files need to be and what happens to the files. Is using `addJavaScript` and `@JavaScript` really exactly the same still in V14.

**Comment by samie** [comment]
In case it matters, it would be good to indicate which mode a documentation applies. E.g. 
- HTML import = compatibility mode
- JS import = npm mode

**Comment by samie** [comment]
Suggestion for clarifying this in V14: Add an info box explaining which type of project this applies to.

> This documentation applies to Vaadin 14 compatibility mode using Bower and HTML imports. If you are using npm and JsModule, please consult this documentation instead: <LINK TO DOC>

and similarly:

> This documentation applies to Vaadin 14 (npm mode) using Bower and HTML imports. If you are using compatibility mode with Bower and HTML imports, please consult this documentation instead: <LINK TO DOC>
