### ISSUE TITLE
Missing link id #maven-plugin on V14 migration guide

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow-and-components-documentation#812]
The add-on migration guide https://vaadin.com/docs/v14/flow/v14-migration/v14-addon-guide.html has a hyperlink to https://vaadin.com/docs/v14/flow/v14-migration/v14-migration-guide.html#maven.plugin but the id `#maven-plugin` doesn't exist on the page `v14-migration-guide.html` so the link just leads to the top of the page.

**Comment by anasmi** [comment]
Fixed by https://github.com/vaadin/flow-and-components-documentation/pull/1238
