### ISSUE TITLE
"embedded vaadin tutorial" example doesn't work

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow-and-components-documentation#852]
Vaadin 14.1.0.alpha4

See the comments under https://vaadin.com/docs/v14/flow/embedding-flow-applications/tutorial-webcomponent-exporter.html

The problem is that `MainAppServlet` catches all requests including static calls to log-in.js and /VAADIN/static/client/client-8D934394E90725193AF0627A952384CD.cache.js . Or there is some other issue since the custom element `<login-form>` seem to be registered: `customElements.get("login-form")` returns something, but the form itself isn't shown.

**Comment by mvysny** [comment]
Additional hints for the tutorial:

1. Please mention that the dev can start off the Skeleton Starter project
2. Mention that `log-in.js` file should be placed into `src/main/webapp`

**Comment by mvysny** [comment]
[skeleton-starter-flow.zip](https://github.com/vaadin/flow-and-components-documentation/files/3761302/skeleton-starter-flow.zip)

My app created from Skeleton using the webcomponent exporter tutorial.

**Comment by tulioag** [comment]
Also " in 6. below " is mentioned 2 times in this tutorial, but I couldn't find it. Using internal links would make it easier to navigate.
