### ISSUE TITLE
Improve “Including Style Sheets” docs

### ISSUE THREAD

**Issue by jouni** [vaadin/flow-and-components-documentation#97]
https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/importing-dependencies/tutorial-include-css.asciidoc

This document should include a warning about using a regular global stylesheet, as that can leak into components in polyfilled browsers.

For example, something like the following would most probably cause havoc in many components:

```css
div {
  margin: 20px;
}
```

In addition, we should document how to included CSS that is correctly scoped in all browsers – basically, to create a HTML import that contains an import for `custom-style.html` (from Polymer) and then a `<custom-style>` declaration including the CSS you want to add.

**Comment by pleku** [comment]
I think we could mayhaps even remove this mentioned tutorial or just mention that this is how css files can be included, but mention that you should not use those and instead just point to the theming chapter. What do you think @jouni ?

**Comment by jouni** [comment]
Someone could be using Flow without using web components with shadow DOM. So I think the documentation could be kept, but add a warning about Shady DOM and pointers to the theming chapter to learn how to work with shadow DOM.
