### ISSUE TITLE
Mention client-side routing in the current Routing and Navigation documentation

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow-and-components-documentation#989]
In the current [Routing and Navigation](https://vaadin.com/docs/v15/flow/introduction/introduction-overview.html) documentation, it doesn't mention client-side routing. 

At least add a link to [client-side routing doc](https://vaadin.com/docs/v15/flow/typescript/creating-routes.html). 
Could also group the current ones into a new section like `Server-side routing`, and make a new one for `Client-side routing`

**Comment by vlukashov** [comment]
Ideas:
 - add a new page to the 'Routing and Navigation' section of the docs (https://vaadin.com/docs/v15/flow/routing/tutorial-routing-annotation.html)
 - rename the section to 'server-side routing and navigation'
 - add an info / note block to the top of every existing page of the 'routing and navigation' section with a link to the 'TypeScript routing' docs page / Vaadin Router docs.
