### ISSUE TITLE
Explain Application Shell concept

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow-and-components-documentation#996]
In [Client Routing](https://vaadin.com/docs/v15/flow/typescript/creating-routes.html)
the Application Shell is mentioned but hasn't been explained so far in the docs.

Make a section explain the concept briefly and link it to [Google](https://developers.google.com/web/fundamentals/architecture/app-shell) for details.

**Comment by vlukashov** [comment]
ToDo:
 - Remove this term from the page. Problem solved :)
 - Create a docs page that describes the ways how to configure the contents of the initial page from Java (AppShellConfigurator).


Related, out of scope for this task
 - still describe the AppShellConfigurator interface in the migration docs (as a replacement for the PageConfigurator interface) see https://github.com/vaadin/flow/issues/7250
 - Update the @PWA docs, and @Push docs to talk about AppShellConfigurator (separate tasks)
