### ISSUE TITLE
Mention VaadinRouterView interface in the general Vaadin Router documentation

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow-and-components-documentation#999]
Once VaadinRouterView([#422](https://app.zenhub.com/workspaces/ccdm-5d413125e27a7b3dba911156/issues/vaadin/vaadin-router/422)) is implemented, we should document it in the general Vaadin Router documentation.

**Comment by vlukashov** [comment]
The page to update: https://vaadin.com/docs/v15/flow/typescript/creating-routes.html.
Check if code snippets need updating.
